spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db
    username: user
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
#  packages-to-scan: br/com/cristal/resource/controller
  swagger-ui:
    path: swagger-ui.html
  api-docs:
    path: /api-docs